updated actions

diff --git a/.github/workflows/zero-trust-pipeline.yml b/.github/workflows/zero-trust-pipeline.yml
--- a/.github/workflows/zero-trust-pipeline.yml
+++ b/.github/workflows/zero-trust-pipeline.yml
@@ -39,19 +39,14 @@ jobs:
           exit-code: '0'                   #set to 1 in case to fail the build
           severity: 'CRITICAL'
 
-      -  name: Get Image Digest
-         id: digest
-         run: |
-           DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest | awk -F'@' '{print $2}')
-           if [[ -z "$DIGEST" ]]; then
-            echo "❌ Error: Image digest not found!"
-            exit 1
-           fi
-           echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_ENV
-
-      - name: Debug Image Digest
+      - name: Retrieve Image Digest
         run: |
-          echo "Extracted digest: $IMAGE_DIGEST"
+          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest | awk -F'@' '{print $2}')
+          if [[ -z "$DIGEST" ]]; then
+            echo "Error: Image digest not found!"
+            exit 1
+          fi
+          echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_ENV
 
       - name: Install Cosign
         run: |
@@ -76,4 +71,6 @@ jobs:
       - name: Push Image to Docker Hub
         run: |
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest
+
+      
 
